prompts:
  - prompts/greeting.txt
  - prompts/math.txt

providers:
  - openai:gpt-3.5-turbo

tests:
  - description: "Test basic greeting response"
    vars:
      name: "John"
    assert:
      - type: "contains"
        value: "Hello"
      - type: "contains"
        value: "John"
      - type: "not-contains"
        value: "error"

  - description: "Test basic math calculation"
    vars:
      number1: 5
      number2: 3
    assert:
      - type: "contains"
        value: "8"
      - type: "contains"
        value: "sum"

output:
  - json
  - csv

outputPath: ./results/promptfoo-results.html 