prompts:
  - prompts/math.txt

providers:
  - openai:gpt-4o-mini
  - openai:gpt-4o
  - anthropic:claude-3-5-sonnet-latest

tests:
  - description: "Test basic math calculation"
    vars:
      number1: 5
      number2: 3
    assert:
      - type: "contains"
        value: "8"
      - type: "contains"
        value: "sum"

output:
  - json
  - csv

outputPath: ./results/promptfoo-results.html 